server:
  port: 9000

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: sa

  devtools:
    livereload:
      enabled: true

---
spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true